author: Noah S. Roberts

project:
  output-dir: _output 
  
execute: 
  enabled: true

  
format:
  html:
    mainfont: Atkinson Hyperlegible
    monofont: Cousine
    toc: true
    embed-resources: true
    self-contained-math: false
    math: true
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&family=Cousine:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

  pdf:
    mainfont: Atkinson Hyperlegible
    monofont: Cousine Nerd Font
    toc: true
    pdf-engine: xelatex
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
